### ISSUE TITLE
NF20 & BUG40: Load Attributes

### ISSUE THREAD

**Issue by to-roth** [DekaAthlos/TINF19C-ModellingWizard#14]

**Comment by PhillipTr01** [comment]
There is a bug, if you don't open the AutomationMLBaseRoleClass after entering the Vendor Name and Device Name. 

Outcome: It doesn't save anything. -> Empty File

**Comment by PhillipTr01** [comment]
Fixed. It now opens the AutomationMLBaseRoleClass Attributes directly on startup.
