### ISSUE TITLE
Edit & Finish SAS 

### ISSUE THREAD

**Issue by to-roth** [DekaAthlos/TINF19C-ModellingWizard#17]

**Comment by DekaAthlos** [comment]
Bei 2.3 Quality Goals, kannst du ruhig erwähnen, dass wir auch versuchen Codeleichen und die allgemeine Qualtität des Codes zu verbessern.

**Comment by Zooaal** [comment]
Hallo ich fände es gut wenn nach Header 2. ein kleiner Text kommt bevor mit 2.1 fortgefahren wird. (3. 4. usw. auch der Fall)

**Comment by DekaAthlos** [comment]
Mega nice bei 3.3, dass du auf: "Clean Code by Robert Cecil Martin" referrenzierst! Kannst sein Buch ruhig bei 6. References hinzufügen.

**Comment by Str1chC0de** [comment]
Finished
