### ISSUE TITLE
Add Final Product Presentation

### ISSUE THREAD

**Issue by DekaAthlos** [DekaAthlos/TINF19C-ModellingWizard#23]
# Add Final Product Presentation

The task is to interview all stakeholders, to get an final presentation for the customer.

The Presentation will be 20 minutes long!
We will have to defend the Project for 10 minutes!

Further Information is to be found:
Projektarbeiten_Info 1.5 - Präsentation 2

**Comment by to-roth** [comment]
Final presentation has been added with push on 20.05.2021.
