### ISSUE TITLE
Tracker for Systemtests

### ISSUE THREAD

**Issue by to-roth** [DekaAthlos/TINF19C-ModellingWizard#26]
In this issue, our product tester records all problems that occure during system tests. Each problem will be a new comment on this issue.

**Comment by PhillipTr01** [comment]
[NF20 - Bug](https://github.com/DekaAthlos/TINF19C-ModellingWizard/issues/14)

**Comment by inf19205** [comment]
"Vendor Name" gets replaced by file path after saving the file

**Comment by inf19205** [comment]
"Save as" is duplicate of "save" and can be removed due to its redundancy and inconsistent functionality.

**Comment by inf19205** [comment]
If no "Device Name" or "Vendor Name" is given and the user clicks on save. 
First the explorer opens and after a location is chosen the program informs the user that the file misses data and can not be saved.
The information about the missing data should be recieved earlier.

**Comment by inf19205** [comment]
If the user opens a new file but cancel in the process.
The Modelling Wizard interface gets cleared and it throws an error.
The data should not be cleared when canceling the process.

**Comment by inf19205** [comment]
The version is still 1.0.0.
Should be changed to at least version 2.0.0.

**Comment by inf19205** [comment]
The dropdown buttons are split in half and only one half opens the dropdown menu.
The whole dropdown button should be one unit and shoul open the dropdown menu.

**Comment by inf19205** [comment]
If the user opens an old file (e.g. file-01.01.2010.amlx), changes nothing and clicks on save,
a new file is generated because the Modelling Wizard plugin changes the date of the file (e.g. new file = file-22.04.2021).
The Modelling Wizard plugin should check if the file already exists and save again under this path,
or the Modelling Wizard plugin should always open the explorer and let the user choose/change the file name.

**Comment by inf19205** [comment]
The explorer opens sometimes and sometimes not after clicking on save.
The explorer should open always.

**Comment by inf19205** [comment]
If the user clicks "Load Library" but cancels the process all libraries in the Modelling Wizard are already deleted.
The libraries should only be deleted if the user confirmed to load the new libraries.

**Comment by inf19205** [comment]
In the Attachments tab - "Add Path" and "Select File" have the same use, but "Add Path" does not work and can therfore be remvoed.

**Comment by to-roth** [comment]
System tests are finished. Tracker can be closed, the information is transferred to the Systemtestreport.
