### ISSUE TITLE
Minimalregel für AML-DDS

### ISSUE THREAD

**Issue by DekaAthlos** [DekaAthlos/TINF19C-ModellingWizard#3]
Kunde soll die Minimalregeln für die Entwicklung bereitstellen. 

Beispiel: Beim Onlinekauf von Artikeln, sind Name und Adresse unabdingbare Felder, welche vom User ausgefüllt werden müssen. 

Name und Adresse sind in diesem Falle Minimalregeln.

**Comment by Zooaal** [comment]
See https://github.com/DekaAthlos/TINF19C-ModellingWizard/wiki/Software-Requirements--Specification#45f50parameter-requirements-
