### ISSUE TITLE
BUG60: mandatory attributes are checked to late

### ISSUE THREAD

**Issue by inf19205** [DekaAthlos/TINF19C-ModellingWizard#30]
If no "Device Name" or "Vendor Name" is given and the user clicks on save.
First the explorer opens and after a location is chosen the program informs the user that the file misses data and can not be saved.
The information about the missing data should be recieved earlier.

**Comment by PhillipTr01** [comment]
Fixed - It checks if the Device Name and the Vendor Name is not null before opening the SaveDialog
