### ISSUE TITLE
BUG80: changes names on old files

### ISSUE THREAD

**Issue by inf19205** [DekaAthlos/TINF19C-ModellingWizard#34]
If the user opens an old file (e.g. file-01.01.2010.amlx), changes nothing and clicks on save,
a new file is generated because the Modelling Wizard plugin changes the date of the file (e.g. new file = file-22.04.2021).
The Modelling Wizard plugin should check if the file already exists and save again under this path,
or the Modelling Wizard plugin should always open the explorer and let the user choose/change the file name.

**Comment by PhillipTr01** [comment]
Fixed - It always opens the saveDialog now. So you can manually overwrite the file or save it as another File
