### ISSUE TITLE
BUG120: deletes all non amlx files

### ISSUE THREAD

**Issue by inf19205** [DekaAthlos/TINF19C-ModellingWizard#43]
If the user opens an amlx file (test.amlx) in the directory of the file a temporary file with .aml is created (file.aml).
After saving the file a new amlx file is created and the temporary aml file is deleted. 
The logic that deletes the temporary .aml file delets all files not ending with .amlx in the directory.
This should be prevented and only the temporary .aml file should be deleted.

**Comment by inf19205** [comment]
This bug appears also if the user creates a new file and saves it.

**Comment by PhillipTr01** [comment]
Fixed.
