### ISSUE TITLE
BUG10: Generic Information Exception

### ISSUE THREAD

**Issue by Zooaal** [DekaAthlos/TINF19C-ModellingWizard#5]
If you enter a new role name under Generic Data, then click on another field and then click again on one of the fields marked blue here, you get an error.
Furthermore an error occurs when clicking on the triangle.
![image](https://user-images.githubusercontent.com/72601495/97195960-30794600-17ac-11eb-8a84-4cf5beabee08.png)

**Comment by PhillipTr01** [comment]
Fixed by catching this exception.
