### ISSUE TITLE
Check Lessons-Learned

### ISSUE THREAD

**Issue by DekaAthlos** [DekaAthlos/TINF19C-ModellingWizard#64]
Hallo Liebes Team,

ich habe die Lessons-Learned einmal aus meiner Sicht zusammengefasst und die Stichpunkte die wir gesammelt haben ausformuliert. Ich würde euch bitten, da einmal drüber zu fliegen, da ich bei einigen Punkten näher ins Detail gegangen bin. Falls etwas nicht stimmen sollte oder noch klärungsbedarf hat, einfach per WA oder mithilfe der Comments bei mir melden!

**Comment by to-roth** [comment]
Sehr schöne Ausformulierung aller Punkte, ich habe nichts hinzuzufügen und finde es perfekt!

**Comment by PhillipTr01** [comment]
Sehr gut geschrieben! Das ist perfekt so.

**Comment by inf19205** [comment]
Formulierung ist super und deckt alle Punkte ab, habe nichts hinzuzufügen.
